//
// Created by IshimotoKiko on 2021/08/31.
//

#ifndef APPEAL_OBSERVEREVENTLIST_HPP
#define APPEAL_OBSERVEREVENTLIST_HPP
enum class ObserverEventList : int {
  DUMMY = 0,

  TITLE_SCENE = 0x1000,
  TITLE_SCENE_ON_SELECT,

  MAP_SCENE = 0x2000,
  MAP_SCENE__PLAYER_CollisionDetection,
  MAP_SCENE__ENEMY_CollisionDetection,
  MAP_SCENE__SELECT_WARP_START,
  MAP_SCENE__SELECT_WARP_GOAL,

  BATTLE_SCENE = 0x4000,
  BATTLE_SCENE_ESCAPE,
  BATTLE_SCENE_WIN,
  BATTLE_SCENE_LOSE,

  KEYBOARD = 0x10000,
  KEYBOARD__ON_INPUT,
};
#endif    // APPEAL_OBSERVEREVENTLIST_HPP
